[package]
name = "server"
version = "0.1.0"
authors = ["Aatu Hieta <aatu@hieta.fi>"]

[dependencies]
enet = "0.2"
log = "0.4"
env_logger = "0.6"
rmp = "0.8"
rmp-serde = "0.13"
serde = "1.0"
serde_derive = "1.0"